spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/balance_db
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  jackson:
    serialization:
      write-dates-as-timestamps: false
  application:
    name: balance-api

server:
  port: 8080
