server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/balance_db
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true
  jackson:
    serialization.write-dates-as-timestamps: false
  application:
    name: balance-api

app:
  sqs:
    endpoint: http://localhost:4566
    queue-url: http://localhost:4566/000000000000/transacoes-financeiras-processadas
    region: sa-east-1
    max-messages: 10
    wait-seconds: 10

aws:
  accessKeyId: test
  secretAccessKey: test

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      probes:
        enabled: true   # habilita /health/liveness e /health/readiness
      show-details: never

info:
  app:
    name: balance-api
    description: API de consulta de saldo (desafio Itaú)

logging:
  level:
    org.springdoc: INFO
    software.amazon.awssdk: DEBUG      # troque para INFO se ficar muito verboso
    br.com.itau.challenge.balance.consumer: DEBUG
